[workspace]
members = [
  "flowy-dispatch",
  "flowy-sdk",
  "dart-ffi",
  "flowy-log",
  "flowy-user",
  "flowy-ast",
  "flowy-derive",
  "flowy-test",
    "flowy-sqlite",
    "flowy-database",
]

[profile.dev]
split-debuginfo = "unpacked"
