[workspace]
members = [
  "flowy-dispatch",
  "flowy-sdk",
  "dart-ffi",
  "flowy-log",
  "flowy-user",
  "flowy-ast",
  "flowy-derive",
  "flowy-test",
  "flowy-sqlite",
  "flowy-database",
  "flowy-infra",
  "flowy-workspace",
  "flowy-observable",
  "flowy-editor",
]

[profile.dev]
split-debuginfo = "unpacked"
