version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENVIRONMENT: "production"
    depends_on:
      - db
    ports:
      - 8000:8000
  db:
    image: 'postgres:14'
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - 5433:5432