name: flowy_infra_ui
description: A new flutter plugin project.
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # Thirdparty packages
  textstyle_extensions: '2.0.0-nullsafety'
  dartz: '0.10.0-nullsafety.2'
  provider: ^5.0.0
  styled_widget: '>=0.3.1'
  equatable: '>=2.0.2'
  animations: ^2.0.0
  # Flowy packages
  flowy_infra:
    path: ../flowy_infra

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flowy_infra_ui
        pluginClass: FlowyInfraUiPlugin
      ios:
        pluginClass: FlowyInfraUiPlugin
      macos:
        pluginClass: FlowyInfraUiPlugin
      windows:
        pluginClass: FlowyInfraUiPlugin
      web:
        pluginClass: FlowyInfraUiWeb
        fileName: flowy_infra_ui_web.dart