name: keyboard_web
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_web_plugins:
    sdk: flutter

  keyboard_platform_interface:
    path: ../keyboard_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: KeyboardPlugin
        fileName: keyboard_web