[package]
name = "flowy-ot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecount = "0.6.0"

[dev-dependencies]
criterion = "0.3"
rand = "0.7.3"
